name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 1.0.0+2
homepage: https://github.com/hpoul/dart_logging_appenders/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  logging: '>=1.0.0 <2.0.0'
  dio: ">=4.0.0 <5.0.0"
  intl: ">=0.17.0 <1.0.0"
  clock: ">=1.1.0 <2.0.0"

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
  mockito: ^5.0.0
  fake_async: ^1.2.0
  path: ^1.8.0
  build_runner: ^1.11.1

dependency_overrides:
  pedantic: ^1.8.0+1

