name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki, graylog (gelf)).
version: 1.2.0+1
homepage: https://github.com/hpoul/dart_logging_appenders/
screenshots:
  - description: Colored console output
    path: doc/screenshot.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  logging: '>=1.2.0 <2.0.0'
  dio: ">=5.2.0 <6.0.0"
  intl: ">=0.17.0 <1.0.0"
  clock: ">=1.1.0 <2.0.0"

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
  mockito: ^5.4.4
  fake_async: ^1.3.1
  path: ^1.8.3
  build_runner: ^2.4.8
