name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 0.3.1
homepage: https://github.com/hpoul/dart_logging_appenders/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: '>=1.0.0 <2.0.0'
  logging: '>=0.11.3+2 <1.0.0'
  dio: '>=2.1.0 <3.0.0'
  rxdart: '>=0.23.0 <1.0.0'
  intl: '>=0.15.0 <1.0.0'
  clock: '>=1.0.0 <2.0.0'
  io: '>=0.3.0 <1.0.0' # For Ansi colors.

dev_dependencies:
  test: ">=1.5.0 <2.0.0"
  pedantic: '>=1.5.0 <2.0.0'
  mockito: ^4.1.0
  fake_async: ^1.0.1
  path: '>=1.6.0 <2.0.0'

dependency_overrides:
  pedantic: ^1.8.0+1

# The following section is specific to Flutter.
flutter:
